### ISSUE TITLE
custom cell style for dates

### ISSUE THREAD

**Issue by amped77** [rabanti-github/PicoXLSX#13]
Hi, 

How do you define a cell style custom format for a date ? I wanted to make the cell style for a date as yyyy.mm.dd  

Regards,

**Comment by amped77** [comment]
never mind stupid of me hehehe finally made it to work 

Style style = new Style();
                            style.CurrentNumberFormat.Number = NumberFormat.FormatNumber.custom;
                            style.CurrentNumberFormat.CustomFormatID = 180;
                            style.CurrentNumberFormat.CustomFormatCode = "yyyy.mm.dd";
                            WS.AddNextCell(mydate, style);

**Comment by rabanti-github** [comment]
Glad you could bring it to work.
I consider to add more documentation or at least an additional demo to demonstrate this, since custom styling is quite complicated.
