### ISSUE TITLE
Merged cells style border lost?

### ISSUE THREAD

**Issue by semenenkov** [rabanti-github/PicoXLSX#16]
Hello,

It looks like merged cell style keeps borders only for top-left cell, does not matter in which order value, style and merge happened:

 ```
            var style = new Style();
            style.CurrentBorder.RightStyle = Style.Border.StyleValue.medium;

            var wb = new Workbook(true);
            var sh = wb.CurrentWorksheet;

            int xy = 1;
            // Value, Merge, Style
            sh.AddCell("V,M,S", xy, xy);
            sh.MergeCells(new Cell.Address(xy, xy), new Cell.Address(xy, xy + 1));
            sh.SetStyle(new Cell.Address(xy, xy), new Cell.Address(xy, xy + 1), style);

            xy = 3;
            // Value, Style, Merge
            sh.AddCell("V,S,M", xy, xy);
            sh.SetStyle(new Cell.Address(xy, xy), new Cell.Address(xy, xy + 1), style);
            sh.MergeCells(new Cell.Address(xy, xy), new Cell.Address(xy, xy + 1));

            xy = 5;
            // no Value, Style, Merge
            sh.SetStyle(new Cell.Address(xy, xy), new Cell.Address(xy, xy + 1), style);
            sh.MergeCells(new Cell.Address(xy, xy), new Cell.Address(xy, xy + 1));

            xy = 7;
            // no Value, Merge, Style
            sh.MergeCells(new Cell.Address(xy, xy), new Cell.Address(xy, xy + 1));
            sh.SetStyle(new Cell.Address(xy, xy), new Cell.Address(xy, xy + 1), style);

            wb.SaveAs("c:\\temp\\merge.xlsx");`
```

![изображение](https://user-images.githubusercontent.com/8459004/155736905-b5de04ce-84a5-49a6-8f31-5fb88945789f.png)

I was also trying to assign style only to left-top corder before merge in hope that it will be applied to the whole merged cell - no luck as well.

Is it a bug or this needs to be written in some other way?

**Comment by rabanti-github** [comment]
Hello,
Usually, in merged cells, only the "outer" cells are considered. However, I cannot say what happens with styles. Have not tested this scenario so far.
I will have a look into it.

**Comment by rabanti-github** [comment]
Hello,
There are two issues:
1. There is a bug in the style class of the library. Quite hidden but easy to fix (already done)
2. You have to set the border styles a little bit different than in your example (I will tell you how to do this)

Technically, I could already fix the issue. However, I have to create a patch, port it to NanoXLSX and NanoXLSX4j and have to deploy a NuGet package. This may take 1-2 days.

As soon as the patch is deployed, it should be possible to add borders around merged cells as follows:
```
            // Style for the upper cell (border at left, right and top)
            var upperStyle = new Style();
            upperStyle.CurrentBorder.LeftStyle = Border.StyleValue.medium;
            upperStyle.CurrentBorder.TopStyle = Border.StyleValue.medium;
            upperStyle.CurrentBorder.RightStyle = Border.StyleValue.medium;

            // Style for the lower cell (border at left, right and bottom)
            var lowerStyle = new Style();
            lowerStyle.CurrentBorder.RightStyle = Border.StyleValue.medium;
            lowerStyle.CurrentBorder.BottomStyle = Border.StyleValue.medium;
            lowerStyle.CurrentBorder.LeftStyle = Border.StyleValue.medium;

            // Note: If merged cells reach over more than 2 cells, 1 or 2 styles where
            // the left and right border, and/or the top and bottom border are
            // defined must be crated and assigned to the intermediate cells

            var wb = new Workbook(true);
            var sh = wb.CurrentWorksheet;

            int xy = 1;
            // Value, Merge, Style
            sh.AddCell("V,M,S", xy, xy);
            sh.MergeCells(new Address(xy, xy), new Address(xy, xy + 1));
            sh.SetStyle(new Address(xy, xy), upperStyle);
            sh.SetStyle(new Address(xy, xy + 1), lowerStyle);
```

Its not very beautiful but maybe I will add basic styles or a helper function to make the style definition easier.

**Comment by rabanti-github** [comment]
Sorry about the delay.
I am investigating currently another bug that I want to fix, and release the patch with the one of this issue in the same release. I hope It's done this week.

**Comment by semenenkov** [comment]
No problem, thanks for update!
Not sure if it is the same issue or not but I've noticed another thing in your last example.
If we comment "sh.MergeCells" - bottom border from the lowerStyle is lost and replced with top border of the upperStyle. And if we comment "upperStyle.CurrentBorder.TopStyle" then bottom border appears.

**Comment by rabanti-github** [comment]
Hi, I just released v2.11.2. The Nuget package should be available in a few minutes.
Can you check whether they are still issues with the border styles?
Let me know if there is something not working as excepted. I will release another patch then.
Thank you in advance

**Comment by semenenkov** [comment]
Hi,
Thanks for update!
I've checked this with your last example of "correct" style assignment (upper and lower cells separately) - border shown properly but cells are not merged:
![изображение](https://user-images.githubusercontent.com/8459004/157760704-27ec34f2-58bc-417b-bf8e-d2c2bd95f491.png)
so it is not possible to say whether border for the merged cell is working or not. But it looks like better than before - upper and lower borders do not affect each other across styles.

**Comment by semenenkov** [comment]
Just a little note regarding importance of this for me right now, to let you choose right priority for this.
I am currently not waiting for this fix, but will be happy to check it again.
After I reported this issue I rewritten all my reports from Interop to Pico, because border was very nice to have but not required. Then I've checked what else I can try and found LargeXlsx. I've decided to try it because it even more little than Pico and as I understand it it does not keep lot of things in memory and puts content to disk during file generation - this was also useful because my apps are x86 and size of data can be very large. I've tried it, there was no border issues and I've rewritten all reports to LargeXlsx.
Your lib looks very promising, I'm sorry that I finally used something else. Who knows, may be I'll face with some issues in LargeXlsx and will have to return back to Pico.

It's more like private message not related to issue itself, I'll remove it in day or two, just wanted to let you know where am I with all this stuff.

**Comment by rabanti-github** [comment]
Hi,
Sorry about he long delay. I was quite busy.
I checked the code again and tried to generate a file with the sample code, stated in my comment of Feb. 27. In my case, the cells were merged. So, the fine line in the picture above is not visible and you can only select one (merged cell).
Can you post your actual sample code and have you updated to the latest version?

Thank you in advance

**Comment by semenenkov** [comment]
Hi,

I am sorry I don't know what it was. I've checked both the latest version and 2.11.2 and it works as expected. I was playing with the Demo project (not Demo .NET Standard) and it doesn't have Build checked in Configuration Properties - may be that's was the reason and I was running some old code, not sure.
So I think this issue is resolved, thank you!
