### ISSUE TITLE
Bug SetWoorkbookProtection

### ISSUE THREAD

**Issue by Popajul** [rabanti-github/PicoXLSX#18]
Hi, i think  there is a bug here : 
![image](https://user-images.githubusercontent.com/85107357/183245775-2315180f-0345-4773-a7b4-2d9cb42eebb5.png)
a white space is missing in workkbook.xml file before workBookPassword property.
this bug corrupts the xlsx file when user try to set workbookProtection.

**Comment by rabanti-github** [comment]
Hello, Thanks for the report. I am looking into that and will hopefully provide a patch as soon as possible

**Comment by rabanti-github** [comment]
The bug was fixed with v2.11.5. The NuGet package is already available.
Thanks again for the report. Please re-open the issue or create a new one, if something is not working as expected
