### ISSUE TITLE
Do you have a Plan to read excel file?

### ISSUE THREAD

**Issue by visualczm** [rabanti-github/PicoXLSX#21]
Hi，
Do you have a Plan to read excel file?

like  this
https://[github.com](https://github.com/shps951023/MiniExcel)/shps951023/MiniExcel

**Comment by rabanti-github** [comment]
Hi, [NanoXLSX](https://github.com/rabanti-github/NanoXLSX) is capable to read Excel files (what can be written is what can be read). NanoXLSX is recently the more active project and will supersede PicoXLSX in future versions.

**Comment by visualczm** [comment]
Wonderful, That's good news
I'll get to know
