### ISSUE TITLE
Cells' style are not retain when merging cells

### ISSUE THREAD

**Issue by DCourtel** [rabanti-github/PicoXLSX#9]
Hi, when merging several cells, for which the first has an applied style, the merged cell doesn't have any style applied.
The method «ResolveMergedCells» always replace the style of ALL CELLS by the MergeCellStyle (which is empty). 
```C#
if (pos != 0)
   {
      cell.DataType = Cell.CellType.EMPTY;
   }
   cell.SetStyle(mergeStyle);
```
To preserve the style of the first cell, it should be:
```C#
if (pos != 0)
   {
      cell.DataType = Cell.CellType.EMPTY;
      cell.SetStyle(mergeStyle);
   }
````

**Comment by rabanti-github** [comment]
Hi
Thank you for the report and the provided fix.
The bug was fixed with commit 75cc06e.

All NuGet Packages (PicoXLSX, NanoXlsx) as well as the  Java artifacts (PicoXLSX4j, NanoXLSX4j) will be available in a few minutes.

Please let me know if something is not workig as expected.
